[package]
name = "hitman-commons"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.61"
tryvial = "0.2.0"
rpkg-rs = { version = "1.2.0", optional = true }
serde = { version = "1.0.203", features = ["derive"], optional = true }
serde_json = { version = "1.0.120", optional = true }
serde-hex = { version = "0.1.0", optional = true }
md5 = "0.7.0"
specta = { version = "=2.0.0-rc.7", optional = true }
brotli-decompressor = { version = "4.0.1", optional = true }
serde-smile = { version = "0.2.1", optional = true }
hashbrown = { version = "0.14.5", features = ["serde"], optional = true }
tonytools = { version = "0.6.0", optional = true}
schemars = { version = "0.8.21", optional = true }
registry = { version = "1.2.3", optional = true }
keyvalues-serde = { version = "0.2.1", optional = true }
itertools = { version = "0.13.0", optional = true }
home = { version = "0.5.9", optional = true }
rune = { version = "0.13.4", optional = true }
better-rune-derive = { git = "https://github.com/atampy25/better-rune-derive", optional = true }
serde_with = { version = "3.11.0", optional = true }
glacier-texture = { version = "1.0.0", optional = true, default-features = false }

[features]
schemars = ["dep:schemars"]
rpkg-rs = ["dep:rpkg-rs"]
glacier-texture = ["dep:glacier-texture"]
tonytools = ["dep:tonytools"]
serde = ["dep:serde", "dep:serde-hex"]
resourcelib = ["dep:serde_json"]
specta = ["serde", "dep:specta"]
hash_list = [
    "serde",
    "dep:brotli-decompressor",
    "dep:serde-smile",
    "dep:hashbrown",
]
game_detection = [
    "serde",
    "dep:registry",
    "dep:serde_json",
    "dep:keyvalues-serde",
    "dep:itertools",
    "dep:home",
]
rune = ["dep:rune", "dep:better-rune-derive", "dep:serde_with"]
